name: Automate Pulling on server
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Pull from server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          whoami
          ./script.sh
